' Generated by Instalar VibeToolkit.cmd
Option Explicit

Dim fso
Dim shell
Dim scriptDir
Dim psScript
Dim targetPath
Dim powerShellExe
Dim innerCommand
Dim command

Set fso = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")

scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
psScript = fso.BuildPath(scriptDir, "project-bundler-headless.ps1")

If Not fso.FileExists(psScript) Then
    MsgBox "Arquivo obrigatorio nao encontrado: " & psScript, vbCritical, "VibeToolkit"
    WScript.Quit 1
End If

targetPath = "."
If WScript.Arguments.Count > 0 Then
    targetPath = Trim(CStr(WScript.Arguments(0)))
    If Len(targetPath) = 0 Then
        targetPath = "."
    End If
End If

powerShellExe = ResolvePowerShellExecutable(shell, fso)
If Len(powerShellExe) = 0 Then
    MsgBox "PowerShell nao encontrado no sistema.", vbCritical, "VibeToolkit"
    WScript.Quit 1
End If

innerCommand = Quote(powerShellExe) & _
    " -NoProfile -ExecutionPolicy Bypass -File " & Quote(psScript) & _
    " -Path " & Quote(targetPath)

command = "cmd.exe /k " & Quote(innerCommand)

shell.Run command, 1, False

Function ResolvePowerShellExecutable(shellObject, fileSystemObject)
    Dim commandPath
    Dim candidates
    Dim i

    commandPath = shellObject.ExpandEnvironmentStrings("%ProgramFiles%\PowerShell\7\pwsh.exe")
    If fileSystemObject.FileExists(commandPath) Then
        ResolvePowerShellExecutable = commandPath
        Exit Function
    End If

    commandPath = shellObject.ExpandEnvironmentStrings("%ProgramW6432%\PowerShell\7\pwsh.exe")
    If fileSystemObject.FileExists(commandPath) Then
        ResolvePowerShellExecutable = commandPath
        Exit Function
    End If

    commandPath = shellObject.ExpandEnvironmentStrings("%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe")
    If fileSystemObject.FileExists(commandPath) Then
        ResolvePowerShellExecutable = commandPath
        Exit Function
    End If

    candidates = Array("pwsh.exe", "powershell.exe")
    For i = LBound(candidates) To UBound(candidates)
        commandPath = ResolveCommandPath(shellObject, candidates(i))
        If Len(commandPath) > 0 Then
            ResolvePowerShellExecutable = commandPath
            Exit Function
        End If
    Next

    ResolvePowerShellExecutable = ""
End Function

Function ResolveCommandPath(shellObject, commandName)
    Dim execObject
    Dim resolved

    On Error Resume Next
    Set execObject = shellObject.Exec("cmd.exe /c where " & commandName)
    If Err.Number <> 0 Then
        Err.Clear
        ResolveCommandPath = ""
        Exit Function
    End If
    On Error GoTo 0

    If execObject.StdOut.AtEndOfStream Then
        ResolveCommandPath = ""
        Exit Function
    End If

    resolved = Trim(execObject.StdOut.ReadLine)
    If Len(resolved) = 0 Then
        ResolveCommandPath = ""
    Else
        ResolveCommandPath = resolved
    End If
End Function

Function Quote(value)
    Quote = Chr(34) & value & Chr(34)
End Function